- src/Path.cpp
- src/ocpn_draw_pi.cpp
- src/pathmanagerdialog.cpp
Show Delete All button when no paths selected
> Show pencil after clicking toolbar icon

- CMakeLists.txt
- include/PointMan.h
- include/ocpn_draw_pi.h
- ocpninclude/ocpn_plugin.h
- src/ODPoint.cpp
- src/PointMan.cpp
- src/ocpn_draw_pi.cpp
API changes fix for toolbardown
Add in EdgePan
Remove styles and replace with GetIcon_Plugin
> Boundary api change

- include/ocpn_draw_pi.h
- ocpninclude/chart1.h
- ocpninclude/ocpn_plugin.h
- src/ODEventHandler.cpp
- src/ODPoint.cpp
- src/ODPointPropertiesImpl.cpp
- src/ocpn_draw_pi.cpp
- src/pathmanagerdialog.cpp
Handle dimming of properties box
> Double click item to bring up properties

- src/ODEventHandler.cpp
- src/ODdc.cpp
- src/ocpn_draw_pi.cpp
Fix up boundary move after create and display of floating toolbar
> Fix up move boundary

- src/ODdc.cpp
Fix error is printing error message for Tessellation
> Fix error message with Tessellation

- Forms/ODPointPropertiesDialog.cpp
- Forms/ODPointPropterties.fbp
- Forms/ODPropertiesDialog.fbp
- Forms/ODPropertiesDialogDef.cpp
- src/ODPoint.cpp
- src/ODPointPropertiesDialog.cpp
- src/ODPropertiesDialogDef.cpp
- src/ODRolloverWin.cpp
- src/ocpn_draw_pi.cpp
Use new API for fonts of rollovers (currently only path/boundary)
Change section for storing all information to Settings/ocpn_draw_pi
> Fix assert errors on Properties and Point Properties dialogs

- CMakeLists.txt
- Forms/ODPropertiesDialog.fbp
- Forms/ODPropertiesDialogDef.cpp
- cmake/PluginLocalization.cmake
- ocpnsrc/ocpndc.cpp
- po/ca.po
- po/cs.po
- po/da.po
- po/de.po
- po/el.po
- po/es.po
- po/et.po
- po/fi.po
- po/fr.po
- po/gl.po
- po/hu.po
- po/it.po
- po/nb.po
- po/nl.po
- po/ocpn_draw_pi.pot
- po/pl.po
- po/pt.po
- po/ru.po
- po/sv.po
- po/tr.po
- po/vi.po
- po/zh.po
- src/ODPropertiesDialogDef.cpp
- src/ODPropertiesDialogImpl.cpp
> Fix display of 'Path' in preferences dialog

- CMakeLists.txt
- include/PIL.h
- src/EBL.cpp
- src/PIL.cpp
- src/ocpn_draw_pi.cpp
> Fix PIL Index line selectable after move

- src/BoundaryMan.cpp
- src/GZ.cpp
- src/GZMan.cpp
- src/ODdc.cpp
- src/ocpn_draw_pi.cpp
Hi,
These fixes don't apply to OSX only.
Regards
Didier
> Unix error too

- src/Boundary.cpp
Hi
Plug a small memory leak.
Regards
Didier
> Boundary::Draw memory leak

- src/ODToolbarImpl.cpp
Hi,
Likely unchanged variable name after copy and paste.
Regards
Didier
> copy and paste error

- src/Boundary.cpp
- src/EBLProp.cpp
- src/GZProp.cpp
- src/ODEventHandler.cpp
- src/ODPointPropertiesImpl.cpp
- src/ODToolbarImpl.cpp
- src/ODicons.cpp
- src/PILProp.cpp
- src/PathMan.cpp
- src/ocpn_draw_pi.cpp
hi
Various errors found by valgrind
> Valgrind errors

- src/EBL.cpp
- src/GZ.cpp
- src/ODJSON.cpp
Hi,
these are real errors founds coverity at least to me.
Regards
Didier
> Real coverity errors

- include/ODMarkIcon.h
- src/PointMan.cpp
Hi,
two regression with the new day/night code:
-  wasn't finding point X icon (hidden OD point).
- leaking textures memory.
Regards
Didier
> Day night fixes

- src/PathMan.cpp
Hi,
Trivial stuff, remove a duplicate call to DeleteConfigPath.
Regards
Didier
> Saving into ODnavobj.xml.changes is already done in DeletePath

- src/ODNavObjectChanges.cpp
- src/ODPointPropertiesImpl.cpp
Hi
For boundary an text points color isn't set on update or loading xml files
Regards
Didier
> Color change

- CMakeLists.txt
- src/ODEventHandler.cpp
- src/pathmanagerdialog.cpp
Fix showing boundary points in boundary after hiding
> Fix show/hide layer

- src/ODEventHandler.cpp
- src/ODLayer.cpp
- src/ocpn_draw_pi.cpp
Hi,
small fixes for latest commits.
Regards
Didier
> Small errors

- include/BoundaryMan.h
- include/PointMan.h
- src/BoundaryMan.cpp
- src/ODAPI.cpp
- src/PointMan.cpp
Hi,
FindPathByGUID is a linear search but we already have a pointer to the result.
It's internal to draw so it could be used safely.
Regards
Didier
> speedup FindLineCrossingBoundary

- appveyor.yml
- src/ocpn_draw_pi.cpp
+ A trivial typo fix to make the code build
> Appveyor update for O5

- .travis.yml
- buildosx/InstallOSX/ocpn_draw_pi.pkgproj.in
Hi,
add OSX to travis build.
Note: this PR doesn't us O version in pkg name.
Regards
Didier
> travis OSX

- manual/site.yml
From odraw_pi to ocpn_draw_pi
Sorry
> Update site.yml  change  edit_url  to conforrm

- manual/site.yml
> Update site.yml  fix start_page
